### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by 27escape** [ddmitov/camel-harness#1]
I have run _npm install_ in resources/app and then _npm start_ but I get

`> CamelHarness.js-Demo-Electron@0.0.1 start /home/kmulholland/external_git/camel-harness/resources/app

> electron main.js
> `

**Comment by ddmitov** [comment]
Hi Kevin,

CamelHarness.js is tested without npm and only with a stand-alone Electron or NW.js.

To use it with Electron:
1. Create a new folder and name it, for example, 'camel-harness',
2. Download the Electron binary package for your operating system from https://github.com/electron/electron/releases,
3. Extract the downloaded Electron package inside your previously created 'camel-harness' folder,
4. Download the CamelHarness.js source package from GitHub,
5. Extract the downloaded CamelHarness.js source package and copy its 'resources' subfolder in the 'camel-harness' folder merging it with the 'resources' subfolder of Electron,
6. start the Electron binary inside the 'camel-harness' folder.

Please excuse me that this simple procedure is not explained inside the README.md. This has to be corrected soon.

With all my best wishes,
Dimitar Mitov

**Comment by ddmitov** [comment]
The documentation is now updated and I consider the issue closed.

**Comment by 27escape** [comment]
Thank you very much, I will try it out as soon as I have a free moment

kevin
