### ISSUE TITLE
Have you seen Valence?

### ISSUE THREAD

**Issue by hoytech** [ddmitov/camel-harness#2]
Hi! Neat project. I've been experimenting with some similar ideas for a while.

I'm just curious if you've seen my module Valence, and if so were there any issues preventing you from using it?

Perl module: https://metacpan.org/pod/Valence
Javascript bridge: https://github.com/hoytech/valence

Regards,

Doug

**Comment by ddmitov** [comment]
Hi Doug,

I did come across your project and your presentation '"Native" GUIs with perl and HTML' some time ago. I just tested your module and it works OK. I installed all dependencies using 'cpanm' with no hassle and the example code for the Valence module starts normally the Electron binary.
The only warning I receive is:
AnyEvent::Handle uncaught error: Broken pipe at /usr/lib/x86_64-linux-gnu/perl5/5.20/AnyEvent/Loop.pm line 248.
I suppose this is specific to my distribution. I plan to update soon anyway. It seems harmless right now.

What stopped me using Valence when I first discovered it was the entry point for the users - they have to start a Valence-based application by calling a Perl script from the command line and we know that many users don't like the command line. But that being said, your approach enables the view part (Electron) to 'speak' constantly to the controller part (Perl) and vice versa using real event loop, which is the major advantage of Valence.

It is also important for me that a Valence-based application is self-sufficient and physically portable like John Haller's PortableApps. I think that a kind of simple binary loader or a PAR-packed executable with the binary dependencies in additional folder (is this possible?) could make Valence more user-friendly and physically portable at the same time. This is worth of research and testing.

CamelHarness.js, on the other side, can not 'speak' to a Perl script once it has started - users can see the output in real time, but nothing more. The idea is that an application using CamelHarness.js starts one or more Perl scripts many times for the many actions the user can take during a single session. So CamelHarness.js implements the controller logic in JavaScript, but you can still put all your business logic in Perl, despite the fact that the Electron binary is the user's entry point and Perl scripts are child processes of the Node process inside Electron.

With all my best wishes,
Dimitar Mitov

**Comment by hoytech** [comment]
Hi Dimitar,

Thank you for your thoughtful response. I agree that CamelHarness.js and Valence are 2 different approaches, either of which might be the best choice for a particular app. Your perl-executing-browser project also seems quite interesting. The way I'm thinking about it now is that Valence is best if you have an (async) perl app that you want to add a GUI to, and CamelHarness.js is best if you have a javascript app that you want to invoke perl code from.

In terms of user-friendliness, I completely agree not all users will be comfortable with command-line apps. You're right I haven't done much work on packaging up Valence apps into self-contained packages. I think that PAR might work (although PAR extracts things into places like /tmp/ so it might need some minor changes).

Sorry to hear Valence didn't work on your platform. Usually the "broken pipe" error on startup is a failure to run the electron binary for some reason. If you enable debug mode (ie `VALENCE_DEBUG=2 perl myapp.pl`) it might show some more details. I've added a ticket to Valence to add better reporting in this case: https://github.com/hoytech/Valence-p5/issues/2

Best regards,

Doug

**Comment by ddmitov** [comment]
Hi Doug,

I must say that I did start successfully the test script of Valence and the browser window of Electron emerged with 'Hello world!" without any visible problem despite the error message I sent you. Probably my wording was not clear enough.

I think packing everything inside a PAR-packed executable, including the 100+ MB Electron binary, will be a performance penalty when starting the application, so it will be nice if a PAR-packed binary could somehow 'use lib' the Alien-Electron module from an external folder. As you mentioned, probably this requires some changes in the PAR routines. 

Another option is a loader binary for Valence-based applications. It is worth the effort and should not be complicated at all. It will have to set the PERLLIB or PERL5LIB environment variable pointing to a portable 'lib' folder and then start the main script. I would implement it in C for Linux or NSIS for Windows to reduce dependencies to the minimum. Statically linked Qt is also an option, but probably an overkill.

Concerning Perl Executing Browser, I am also open to any suggestions or feedback.

With all my best wishes,
Dimitar Mitov
